# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NormalTestAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NormalTestAPI

	pod 'Alamofire'
	pod 'SwiftyJSON'

  target 'NormalTestAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NormalTestAPIUITests' do
    # Pods for testing
  end

end
